.cic_eth_variables:
    variables:
        APP_NAME: cic-eth

        #build-mr-cic-eth:
        #    extends:
        #        - .cic_eth_variables
        #        - .py_build_target_dev
        #    rules:
        #    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        #      changes:
        #          - apps/cic-eth/**/*
        #      when: always

test-mr-cic-eth:
    stage: test
    tags:
      - integration
    extends:
        - .cic_eth_variables
    cache:
      key:
        files:
        - test_requirements.txt
      paths:
      - /root/.cache/pip
    image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/$APP_NAME:$MR_IMAGE_TAG
    script:
        - cd apps/$APP_NAME/
        - >
          pip install --extra-index-url https://pip.grassrootseconomics.net:8433
          --extra-index-url https://gitlab.com/api/v4/projects/27624814/packages/pypi/simple
          -r admin_requirements.txt
          -r services_requirements.txt
          -r test_requirements.txt 
        - export PYTHONPATH=. && pytest -x --cov=cic_eth --cov-fail-under=90 --cov-report term-missing tests
    allow_failure: true
    needs: ["build-merge-request"]
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/$APP_NAME/**/*
      when: always

      #build-push-cic-eth:
      #    extends:
      #        - .py_build_push
      #        - .cic_eth_variables
      #    rules:
      #    - if:  $CI_COMMIT_BRANCH == "master"
      #      changes:
      #          - apps/cic-eth/**/*
      #      when: always
