build-test-cic-eth:
  stage: test
  tags:
    - integration
  variables:
    APP_NAME: cic-eth
    MR_IMAGE_TAG: mr-$APP_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - cd apps/cic-eth
    - docker build -t $MR_IMAGE_TAG -f docker/Dockerfile . 
    - docker run $MR_IMAGE_TAG sh docker/run_tests.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/$APP_NAME/**/*
      when: always
