.cic_eth_variables:
    variables:
        APP_NAME: cic-eth
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

.cic_eth_changes_target:
    rules:
        - changes:
            - $CONTEXT/$APP_NAME/*

build-mr-cic-eth:
    extends:
        - .cic_eth_changes_target
        - .py_build_merge_request
        - .cic_eth_variables
    variables:
        PYTHONPATH: .
    after_script:
        - pip install -r test_requirements.txt
        - pytest tests/unit/
        - pytest tests/task/
        - pytest tests/filters/

build-push-cic-eth:
    extends:
        - .py_build_push
        - .cic_eth_variables
        

