.contract-migration-changes-target:
    rules:
        - changes:
            - $CONTEXT/cic-eth/*

build-cic-eth:
    extends:
        - .contract-migration-changes-target
        - .py-build
    variables:
        DOCKERFILE_PATH: cic-eth/docker/Dockerfile

