.cic_eth_variables:
    variables:
        APP_NAME: cic-eth
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

# build-mr-cic-eth:
#     extends:
#         - .py_build_merge_request
#         - .cic_eth_variables

build-mr-unittest-cic-eth:
    extends:
        - .cic_eth_variables
        - .py_build_unittest_merge_request
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    #   changes:
    #   - $CONTEXT/$APP_NAME/**/*
      when: always

test-mr-cic-eth:
    extends:
        - .cic_eth_variables
    stage: test
    image: $CI_REGISTRY_IMAGE/$APP_NAME-test:latest
    script:
        - cd apps/$APP_NAME/
        - pytest tests/unit/
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    #   changes:
    #   - $CONTEXT/$APP_NAME/**/*
      when: always
    

build-push-cic-eth:
    extends:
        - .py_build_push
        - .cic_eth_variables
        

