.cic_eth_variables:
    variables:
        APP_NAME: cic-eth
        DOCKERFILE_PATH: docker/Dockerfile_ci
        CONTEXT: $CI_PROJECT_DIR/apps/$APP_NAME

.cic_eth_changes_target:
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      #changes:
          #- $CONTEXT/$APP_NAME/**/*
      when: always

build-mr-cic-eth:
    extends:
        - .cic_eth_variables
        - .cic_eth_changes_target
        - .py_build_target_dev

test-mr-cic-eth:
    stage: test
    extends:
        - .cic_eth_variables
        - .cic_eth_changes_target
    image: $MR_IMAGE_TAG
    script:
        - cd apps/$APP_NAME/
        - pip install -r test_requirements.txt
        - export PYTHONPATH . && pytest -x --cov=cic_eth --cov-fail-under=90 --cov-report term-missing tests
    needs: ["build-mr-cic-eth"]

build-push-cic-eth:
    extends:
        - .py_build_push
        - .cic_eth_variables
