default:
  image: docker:latest
  tags:
    - cic-runner

variables:
  REGISTRY: registry.gitlab.com/kamikazechaser/cic-monorepo
  DOCKER_BUILDKIT: "1"

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

include:
  - local: 'apps/cic-eth/.gitlab-ci.yml'