include:
  #- local: 'ci_templates/.cic-template.yml' #kaniko build templates
  # these includes are app specific unit tests
  - local: 'apps/cic-eth/.gitlab-ci.yml'
  - local: 'apps/cic-ussd/.gitlab-ci.yml'
  - local: 'apps/cic-notify/.gitlab-ci.yml'
  - local: 'apps/cic-meta/.gitlab-ci.yml'
  - local: 'apps/cic-cache/.gitlab-ci.yml'
    #- local: 'apps/contract-migration/.gitlab-ci.yml'
    #- local: 'apps/data-seeding/.gitlab-ci.yml'

stages:
  - build
  - test
  - deploy 

image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/docker-with-compose:latest  

variables:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1" 
  CI_DEBUG_TRACE: "true"
  SEMVERBOT_VERSION: "0.2.0"

  #before_script:
  #  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

# runs on protected branches and pushes to repo
build-push:
  stage: build
  tags:
    - integration
  #script:
  #  - TAG=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA sh ./scripts/build-push.sh
  script:
    - apk update && apk add git
    - git remote remove origin
    - git remote add origin https://kamikazechaser:$CI_TOKEN@gitlab.com/$CI_PROJECT_PATH
    - curl -o sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
    - chmod +x sbot
    - ./sbot predict version -m git-commit
    - export TAG=$(./sbot predict version)
    - TAG=$TAG sh ./scripts/build-push.sh
    - git tag -a v$TAG -m "ci tagged"
    - git push origin v$TAG
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"
    when: always
