[git]

[git.config]
email = "semverbot@grassroots.org"
name = "semvervot"

[git.tags]
prefix = "v"

[semver]
mode = "git-commit"

[semver.detection]
patch = ["fix", "[fix]", "patch", "[patch]"]
minor = ["minor", "[minor]", "feat", "[feat]", "release", "[release]", "bump", "[bump]"]
major = ["BREAKING CHANGE"]
