services:
  cic-frontend-auth:
    image: registry.gitlab.com/grassrootseconomics/cic-auth-proxy:latest
    environment:
      GPG_TRUSTED_PUBLICKEY_FINGERPRINT: CCE2E1D2D0E36ADE0405E2D0995BB21816313BD5
      GPG_IMPORT_DIR: /usr/src/cic-auth-proxy/meta/tests/testdata/dev/
      GPG_PUBLICKEY_FILENAME: publickeys.asc
      GPG_SIGNATURE_FILENAME: signature.asc
      PROXY_HOST: cic-meta-server 
      PROXY_PORT: 80 
      PROXY_PROTO: http
      PROXY_PATH_PREFIX: "/"
      HOMEDIR: .gnupg
    ports:
      - 8080:80

