# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "key-server"
  namespace: grassroots 
  labels:
    app: "key-server"
spec:
  imagePullSecrets:
    - name: grassroots-registry-dev
  containers:
  - name: key-server 
    image: registry.gitlab.com/grassrootseconomics/devops/key-server:latest
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
    ports:
    - containerPort: 8080
      name:  http
    - containerPort: 8081
      name: http-internal
    volumeMounts:
    - name: pgp-meta-test
      mountPath: "/etc/nginx/html/"
  volumes:
  - name: pgp-meta-test 
    configMap:
      name: pgp-meta-test
      items:
      - key: publickeys.asc
        path: publickeys/index.html
      - key: signature.asc
        path: signature/index.html
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: key-server 
  namespace: grassroots 
spec:
  selector:
    app: key-server 
  type: ClusterIP
  ports:
  - name: http 
    protocol: TCP
    port: 8080
    targetPort: 8080 
  - name: http-internal
    port: 8081
    targetPort: 8081
