FROM nginx:alpine as server

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# copy nginx configuration file
COPY nginx.conf /etc/nginx/

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
