# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-cache-watchers
  namespace: grassroots
  labels:
    app: cic-cache-watchers
  annotations:
      keel.sh/policy: "glob:master-*"
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "@every 5m"
spec:
  selector:
    matchLabels:
      app: cic-cache-watchers
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cic-cache-watchers
        group: cic
        tier: queue
    spec:
      containers:
      - name: cic-cache-tasker
        #image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-cache:master-402b968b-1626300208 # {"$imagepolicy": "flux-system:cic-cache"}
        image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-cache:latest
        imagePullPolicy: Always   
        command: ["/usr/local/bin/cic-cache-taskerd", "-vv"]
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_USER
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_PORT
        - name: DATABASE_ENGINE
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_ENGINE
        - name: DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_DRIVER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_PASSWORD
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: redis-conn-common
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_URL
          valueFrom:
            configMapKeyRef:
              name: redis-conn-common
              key: CELERY_RESULT_URL
        - name: CIC_CHAIN_SPEC
          value: "evm:bloxberg:8996"
        - name: DATABASE_NAME
          value: cic_cache
        - name: ETH_PROVIDER
          value: http://bloxberg-validator.grassroots.svc.cluster.local:8547
        - name: CIC_REGISTRY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-migration-output
              key: CIC_REGISTRY_ADDRESS
        - name: CIC_TRUST_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-migration-output
              key: CIC_TRUST_ADDRESS
      - name: cic-cache-tracker
        #image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-cache:master-402b968b-1626300208 # {"$imagepolicy": "flux-system:cic-cache"}
        image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-cache:latest
        # command: ["/usr/local/bin/cic-cache-trackerd", "-vv", "-c", "/usr/local/etc/cic-cache"]
        command: ["./start_tracker.sh", "-c", "/usr/local/etc/cic-cache", "-vv"]
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CIC_REGISTRY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-migration-output
              key: CIC_REGISTRY_ADDRESS
        - name: CIC_TRUST_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-migration-output
              key: CIC_TRUST_ADDRESS
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_USER
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_PORT
        - name: DATABASE_ENGINE
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_ENGINE
        - name: DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_DRIVER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql-conn-common
              key: DATABASE_PASSWORD
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: redis-conn-common
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_URL
          valueFrom:
            configMapKeyRef:
              name: redis-conn-common
              key: CELERY_RESULT_URL
        - name: DATABASE_NAME
          value: cic_cache
        - name: ETH_PROVIDER
          value: http://bloxberg-validator.grassroots.svc.cluster.local:8547
        - name: CIC_CHAIN_SPEC
          value: "evm:bloxberg:8996"
        - name: SERVER_PORT
          value: "8000"
        - name: ETH_ABI_DIR
          value: /usr/local/share/cic/solidity/abi
        - name: DATABASE_DEBUG
          value: "0"
      restartPolicy: Always
