.cic_cache_variables:
    variables:
        APP_NAME: cic-cache
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile
        CONTEXT: apps

build-mr-cic-cache:
    extends:
        - .py_build_merge_request
        - .cic_cache_variables
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/cic-cache/**/*
      when: always

build-push-cic-cache:
    extends:
        - .py_build_push
        - .cic_cache_variables
    rules:
    - if:  $CI_COMMIT_BRANCH == "master"
      changes:
          - apps/cic-cache/**/*
      when: always
        

