.cic_cache_variables:
    variables:
        APP_NAME: cic-cache
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

.cic_cache_changes_target:
    rules:
        - changes:
            - $CONTEXT/$APP_NAME/*

build-mr-cic-cache:
    extends:
        - .cic_cache_changes_target
        - .py_build_merge_request
        - .cic_cache_variables

build-push-cic-cache:
    extends:
        - .py_build_push
        - .cic_cache_variables
        

