apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bloxberg-validator
  namespace: grassroots
  labels:
    app: bloxberg-validator
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
