
.cic_meta_variables:
    variables:
        APP_NAME: cic-meta
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

.cic_meta_changes_target:
    rules:
        - changes:
            - $CONTEXT/$APP_NAME/*

build-mr-cic-meta:
    extends:
        - .cic_meta_changes_target
        - .py_build_merge_request
        - .cic_meta_variables

build-push-cic-meta:
    extends:
        - .py_build_push
        - .cic_meta_variables
        

