
.cic_meta_variables:
    variables:
        APP_NAME: cic-meta
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile
        CONTEXT: apps

build-mr-cic-meta:
    extends:
        - .py_build_merge_request
        - .cic_meta_variables
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/cic-meta/**/*
      when: always

test-mr-cic-meta:
    extends:
        - .cic_meta_variables
    stage: test
    image: $MR_IMAGE_TAG 
    script:
        - cd /tmp/src/cic-meta
        - npm install --dev 
        - npm run test
        - npm run test:coverage
    needs: ["build-mr-cic-meta"]
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/cic-meta/**/*
      when: always

build-push-cic-meta:
    extends:
        - .py_build_push
        - .cic_meta_variables
    rules:
    - if:  $CI_COMMIT_BRANCH == "master"
      changes:
          - apps/cic-meta/**/*
      when: always
