
.cic_meta_variables:
    variables:
        APP_NAME: cic-meta
        DOCKERFILE_PATH: docker/Dockerfile_ci
        CONTEXT: apps/$APP_NAME

        #build-mr-cic-meta:
        #    extends:
        #        - .py_build_merge_request
        #        - .cic_meta_variables
        #    rules:
        #    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        #      changes:
        #          - apps/cic-meta/**/*
        #      when: always

test-mr-cic-meta:
    stage: test
    tags:
      - integration
    extends:
        - .cic_meta_variables
    image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/$APP_NAME:$MR_IMAGE_TAG 
    script:
        - cd /root
        - npm install --dev 
        - npm run test
        - npm run test:coverage
    allow_failure: true
    needs: ["build-merge-request"]
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/$APP_NAME/**/*
      when: always
