
.cic_meta_variables:
    variables:
        APP_NAME: cic-meta
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile
        IMAGE_TAG: $CI_REGISTRY_IMAGE/$APP_NAME:unittest-$CI_COMMIT_SHORT_SHA

build-mr-cic-meta:
    extends:
        - .py_build_merge_request
        - .cic_notify_variables
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/cic-meta/**/*
      when: always

test-mr-cic-meta:
    extends:
        - .cic_meta_variables
        - .cic_meta_changes_target
    stage: test
    image: $MR_IMAGE_TAG 
    script:
        - cd /tmp/src/cic-meta
        - npm install --dev 
        - npm run test
        - npm run test:coverage
    needs: ["cic-meta-build-mr"]
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/cic-meta/**/*
      when: always

build-push-cic-meta:
    extends:
        - .py_build_push
        - .cic_meta_variables
    rules:
    - if:  $CI_COMMIT_BRANCH == "master"
      changes:
          - apps/cic-meta/**/*
      when: always
