# hhttps://github.com/bitnami/charts/tree/master/bitnami/redis
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis 
  namespace: grassroots
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  chart:
    spec:
      # The name of the chart as made available by the HelmRepository
      # (without any aliases)
      chart: redis
      # A fixed SemVer, or any SemVer range
      # (i.e. >=4.0.0 <5.0.0)
      version: 12.8.3 
      # The reference to the HelmRepository
      sourceRef:
        kind: HelmRepository
        name: bitnami 
        # Optional, defaults to the namespace of the HelmRelease
        namespace: default
  values: 
    cluster:
      slaveCount: 0
    usePassword: false
    metrics:
      enabled: true 
