.cic_notify_variables:
    variables:
        APP_NAME: cic-notify

        #build-mr-cic-notify:
        #    extends:
        #        - .py_build_merge_request
        #        - .cic_notify_variables
        #    rules:
        #    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        #      changes:
        #          - apps/cic-notify/**/*
        #      when: always

test-mr-cic-notify:
    stage: test
    tags:
     - integration
    extends:
     - .cic_notify_variables
    cache:
      key:
        files:
        - test_requirements.txt
        paths:
        - /root/.cache/pip
        image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/$APP_NAME:$MR_IMAGE_TAG
    script:
        - cd apps/$APP_NAME/
        - >
          pip install --extra-index-url https://pip.grassrootseconomics.net:8433
          --extra-index-url https://gitlab.com/api/v4/projects/27624814/packages/pypi/simple
          -r test_requirements.txt 
        - export PYTHONPATH=. && pytest -x --cov=cic_notify --cov-fail-under=90 --cov-report term-missing tests
    allow_failure: true
    needs: ["build-merge-request"]
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/$APP_NAME/**/*
      when: always
