variables:
    APP_NAME: contract-migration
    DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

.this_changes_target:
    rules:
        - changes:
            - $CONTEXT/$APP_NAME/*

build-mr-contract-migration:
    extends:
        - .this_changes_target
        - .py_build_merge_request

build-push-contract-migration:
    extends:
        - .this_changes_target
        - .py_build_push
