.contract_migration_variables:
    variables:
        APP_NAME: contract-migration
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile_ci

# .contract_migration_changes_target:
#     rules:
#         - changes:
#             - $CONTEXT/$APP_NAME/*

.contract_migration_changes_target:
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - $CONTEXT/**/*
      when: always

build-mr-contract-migration:
    extends:
        - .contract_migration_changes_target
        - .py_build_merge_request
        - .contract_migration_variables

build-push-contract-migration:
    extends:
        - .py_build_push
        - .contract_migration_variables
