.contract-migration-changes-target:
    rules:
        - changes:
            - $CONTEXT/contract-migration/*

build-contract-migration:
    extends:
        - .contract-migration-changes-target
        - .py-build
    variables:
        DOCKERFILE_PATH: contract-migration/docker/Dockerfile
