.contract_migration_variables:
    variables:
        APP_NAME: contract-migration
        DOCKERFILE_PATH: $APP_NAME/docker/Dockerfile

.contract_migration_changes_target:
    rules:
        - changes:
            - $CONTEXT/$APP_NAME/*

build-mr-contract-migration:
    extends:
        - .contract_migration_changes_target
        - .py_build_merge_request
        - .contract_migration_variables

build-push-contract-migration:
    extends:
        - .py_build_push
        - .contract_migration_variables
